language: node_js
node_js:
  - "0.10"
env:
  global:
  - DB=mysql
  - TRAVIS_LAUNCHES_SAUCE_CONNECT=true # Tell the karma file that it does not need to launch Sauce connect
  - RAILS_ENV=development
  - secure: fGGzDXTavuBo7KPkuIeBR+Lwqy+/yxqMA9Pi+8mp0RT9e4XU8HVYD23V0NDErXLff8J7aqbOe0/5D5ZiIV0G5MxoXNGx7zsDAO7FwpP902tgYm95SK5yEEWDO/dgP9F/mbZqw7+wrxsdkTDYu8C8A3FZf1nc7nrriYX9ttsgw2E=#SAUCE_URL="http://privly:********-****-****-****-************@ondemand.saucelabs.com:80/wd/hub"(smcgregor/privly-jetpack)
  - secure: Z5po5j3TbRxeOkVs9iNMcVR5vxFc/dzvjpFyJtACyLO+ixrFYGYoX57txyMArbhgZ7xaLuPYE4MKNnISerWXAHokrNd0yGix3Jh/8n3m/CsZOLiW13jfYCQGi9h9R+n4bQzW4r4aloHT9BHvNbSV0cEw36EmqEmeYxBMHP/FjmE=#SAUCE_USERNAME=privly(smcgregor/privly-jetpack)
  - secure: LjHz/jokDOa4cncruGSMDyEum7lbmsfch/NHsESc9Zjk6oLBLb07TYhGGI0q3TZthmnFa29z0YuCShYwgOCHSVJfrsZAvFTs7jATZ/VuQJLtXJrfKX4gyZ8G5c8hJWaBysKP6scPFmg71TzBUaUJod2VijzPlweYeFv4UhDRehY73RAsJopq/WWlQbheZnRK33R0Un26GilmdHUUdqQzkyO1+FwM1TyqpFgRApCp9VQuKnMW63l5pxgcbpDO4sDzIf+ctehAKZijp6yd0Uz5p/aptoIJ2UgkEJzE/tc/v0JP1bqD9wanNbGr3V8Z/9PtUQfoC5iEpzSEKwmjGsCH+qBT7vy5mwjoI31nCw7OWKmAQtE14yztzT8OlJV/kRcMMDZAgoHSlsezxFIiUgQIJ2gVpGqSyKe9l0OljRkAjgNaUUsY/RzJPmcpH1US/Nn8+rcy80GBf4xdfcVcR5tMAhH0sCQXFKku+jMExF+IkziRrRoEuly5yD6kv/YbdFoT8kEgCt4epOS7ayy6lTpdeG8c7U7viCTolLk4892lbOcdcqD37pI+jvykirzGypIevw2VRlu+ORke2MnYnMQokjVk9Q4esc3Dl2GgV/Tk9IZIi4mjGd7Qb1HRPyZFy+CTI81hDloZa8Nhns9z2cIL/lPFxWtgP5h1cM+Njk9+K8U=#SAUCE_URL="http://privly:********-****-****-****-************@ondemand.saucelabs.com:80/wd/hub"(smcgregor/privly-jetpack)
  - secure: h71l3AjoasthHGP58QY1y7bZ9qnuZba8dAjDUsU1ZriDAIbXiqm94bK4O5hEjL2heSzClNOHTXF1/2W3Qf5j89LqY+Qiw1X5sYyGEG6B71eIUVZ71C635lk7iyhEUXHXIu0mJ/L9Ey6HTm9XoKpXgtNIFICHl6mb8hYbXE06+1o3/Ut+yPzGyD/Dg5amQZ6NEMAfSVZI7W3HoepDmjIl/c9lRXmivOZpDh0akQhVrcbJRuIMYsXrO67wV4vLWit9Mgdv2+WphNQIwJu+YwyXfKurjfjE/S2V0dQhXMWMnhNR0O7PEiEWW+lTQroGkXon/n+/gcLeQm5FvHpHM1xmY21O4OQuEggTZlFf2MXyujByt1bqcgNgyAOoTn4TN4K1Ck7g/gmmopYPYLuNnKs6q/p7OucVmbDPbtsu0RanOI39wT5l05PJ6X8MiRnMi/V2EPnJMg7dv7q93OnXs3u5c15QUduG//wN4g6xt6rXlYSD2tCKtkIlJGorX2AKCut0i4DGORQm4dadcClldM2WUfjM+bbNGbPnj98T8oJLf9G7RJPmyOImibgwlDeG3VRtPZEQKOYM4rmCQlWXmH7lG54axfp6/bqQinGJ+hYaUdDXYD3IISphIe77okywp/OaPlbzgj1jJtXfmPsJqvkzlK3jUsjf72FNb4z3bolR9WE=#SAUCE_USERNAME=privly(smcgregor/privly-jetpack)
before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR"
  - git submodule update --init --recursive
  - git clone https://github.com/privly/privly-web.git # clone the webserver
before_script:
  - npm install jpm -g
  - cd ..
  - wget "http://ftp.mozilla.org/pub/firefox/releases/39.0/linux-x86_64/en-US/firefox-39.0.tar.bz2" -O firefox.tar.bz2
  - tar -xjf firefox.tar.bz2 firefox
  - cd $TRAVIS_BUILD_DIR
  - cd node/
  - npm install
  - cd ..
  - cd privly-web
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database privly_test'
  - bundle install #Installs the required gems
  - rake db:create #Creates the Database
  - rake db:schema:load #Loads the Scheme
  - rake db:seed #Seeds the DB
  - "bundle exec rails server -p 3000 &"
  - cd ../chrome/content/privly-applications/
script:
  - "if [ ${TRAVIS_PULL_REQUEST} = 'false' ]; then ruby run_all.rb -p sauce_firefox_extension -r experimental -c http://localhost:3000; fi" # Don't run on pull requests
  - cd $TRAVIS_BUILD_DIR
  - ./run_test.sh

addons:
  sauce_connect: true
